<?php

declare(strict_types=1);

use Bpmore\DocumentA11yCore\VeraPdf\ProcessVeraPdfRunner;
use Bpmore\StatamicA11yDocs\Tests\TestCase;

// Only the addon's own tests need a booted Statamic. The rule sets are
// framework-free and run in milliseconds, which is the whole reason they are
// kept that way.
uses(TestCase::class)->in('Feature');

/**
 * The document fixture corpus: 45 deliberately broken, and deliberately
 * correct, documents generated by tools/build-fixtures.php.
 */
function corpusPath(string $relative = ''): string
{
    $root = __DIR__.'/fixtures/documents';

    return $relative === '' ? $root : $root.'/'.$relative;
}

/** @return array<string, mixed> */
function corpusManifest(): array
{
    static $manifest = null;

    return $manifest ??= json_decode(
        (string) file_get_contents(corpusPath('manifest.json')),
        true,
        512,
        JSON_THROW_ON_ERROR
    );
}

/**
 * Every fixture in the corpus, keyed by path so failures name the file.
 *
 * @return array<string, array<string, mixed>>
 */
function corpusFixtures(?string $format = null): array
{
    $fixtures = [];
    foreach (corpusManifest()['fixtures'] as $fixture) {
        if ($format !== null && $fixture['format'] !== $format) {
            continue;
        }
        $fixtures[$fixture['path']] = $fixture;
    }

    return $fixtures;
}

/**
 * Every rule identifier the corpus mentions, from both `expect` and
 * `expect_absent`. The manifest is the closest thing this project has to a rule
 * registry, so it is what the code is held against.
 *
 * @return list<string>
 */
function corpusRuleIds(?string $format = null): array
{
    $ruleIds = [];

    foreach (corpusManifest()['fixtures'] as $fixture) {
        foreach ($fixture['expect'] as $expectation) {
            $ruleIds[$expectation['rule']] = true;
        }
        foreach ($fixture['expect_absent'] as $ruleId) {
            $ruleIds[$ruleId] = true;
        }
    }

    $ruleIds = array_keys($ruleIds);
    sort($ruleIds);

    if ($format !== null) {
        $ruleIds = array_values(array_filter(
            $ruleIds,
            static fn (string $ruleId): bool => str_starts_with($ruleId, $format.'.'),
        ));
    }

    return $ruleIds;
}

/**
 * PHP files under the given directories, keyed by their path relative to the
 * repository root so a failure names the file.
 *
 * @param  list<string>  $directories
 * @return array<string, string>
 */
function phpSources(array $directories): array
{
    $root = dirname(__DIR__);
    $files = [];

    foreach ($directories as $directory) {
        $iterator = new RecursiveDirectoryIterator($root.'/'.$directory, FilesystemIterator::SKIP_DOTS);
        foreach (new RecursiveIteratorIterator($iterator) as $file) {
            if ($file->getExtension() !== 'php') {
                continue;
            }
            $files[substr($file->getPathname(), strlen($root) + 1)] = $file->getPathname();
        }
    }

    ksort($files);

    return $files;
}

/** The framework-free half of the codebase. */
function sourceFiles(): array
{
    return phpSources(['core']);
}

/** Everything this addon ships, both halves. */
function allSourceFiles(): array
{
    return phpSources(['core', 'src']);
}

/**
 * The namespaced names a PHP file actually references, with comments and string
 * literals excluded.
 *
 * Pest's arch matchers cannot do this job: they resolve a dependency by looking
 * it up among the registered PSR-4 prefixes, so a name shallower than any
 * prefix — `Illuminate`, where the registered prefixes are `Illuminate\Support\`
 * and friends — matches nothing and the expectation passes without testing
 * anything. Reading the tokens does not care how a thing is autoloaded.
 *
 * @return list<string>
 */
function referencedNames(string $file): array
{
    $names = [];

    foreach (token_get_all((string) file_get_contents($file)) as $token) {
        if (! is_array($token)) {
            continue;
        }
        if (in_array($token[0], [T_NAME_QUALIFIED, T_NAME_FULLY_QUALIFIED, T_NAME_RELATIVE], true)) {
            $names[] = ltrim($token[1], '\\');
        }
    }

    return $names;
}

/** A veraPDF report captured from the real binary, kept for testing the parser. */
function veraPdfReport(string $name): string
{
    $path = __DIR__."/fixtures/verapdf/$name.json";

    if (! is_file($path)) {
        throw new RuntimeException("No captured veraPDF report called '$name'.");
    }

    return (string) file_get_contents($path);
}

/** Is the real veraPDF binary on this machine? Most machines have no Java. */
function veraPdfInstalled(): bool
{
    static $installed = null;

    return $installed ??= (new ProcessVeraPdfRunner)->version() !== null;
}

/**
 * The repository root.
 *
 * Not base_path(): under Testbench that is the skeleton application, not this
 * addon. Resolved from this file, which is the one place guaranteed to be
 * loaded from where it actually lives.
 */
function repoPath(string $relative = ''): string
{
    $root = dirname(__DIR__);

    return $relative === '' ? $root : $root.'/'.$relative;
}
